# Update Time: 2024-05-31 01:10
version: "3.4"

services:
  # Grafana
  grafana:
    image: grafana/grafana:latest
    networks: [network_cluster]
    restart: on-failure
    environment:
      # 直接使用Portainer容器内的环境变量
      PUID: 1000
      PGID: 1000       
      TZ: ${TZ}
    volumes:
      - nfs_grafana_data:/var/lib/grafana
      - nfs_grafana_conf:/usr/share/grafana/conf
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_SWARM}`,`grafana.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.grafana.entrypoints=websecure
        - traefik.http.routers.grafana.service=grafana
        - traefik.http.routers.grafana.middlewares=auth,normal-chain@file
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - homepage.group=Metrics & Monitor
        - homepage.name=Grafana
        - homepage.icon=grafana.png
        - homepage.href=https://grafana.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=Grafana
        - homepage.siteMonitor=http://grafana:3000
        - homepage.weight=10
        - homepage.widget.type=grafana
        - homepage.widget.url=http://grafana:3000
        - homepage.widget.username=${HOMEPAGE_GRAFANA_USERNAME}
        - homepage.widget.password=${HOMEPAGE_GRAFANA_PASSWORD}        
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.metrics == true
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
          
  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data --web.console.libraries=/usr/share/prometheus/console_libraries --web.enable-lifecycle --web.console.templates=/usr/share/prometheus/consoles
    networks: [network_cluster]
    restart: on-failure
    environment:
      # 直接使用Portainer容器内的环境变量
      PUID: 0
      PGID: 0 
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nfs_prometheus_conf:/etc/prometheus
      - nfs_prometheus_data:/data
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN_SWARM}`,`prometheus.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.prometheus.entrypoints=websecure
        - traefik.http.routers.prometheus.service=prometheus
        - traefik.http.routers.prometheus.middlewares=auth,normal-chain@file
        - traefik.http.services.prometheus.loadbalancer.server.port=9090
        - homepage.group=Metrics & Monitor
        - homepage.name=Prometheus
        - homepage.icon=prometheus.png
        - homepage.href=https://prometheus.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=Prometheus
        - homepage.siteMonitor=http://prometheus:9090
        - homepage.weight=11
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.metrics == true
      # resources:
      #   limits:
      #     memory: 512M
      #   reservations:
      #     memory: 64M

  # AlertManager
  alertmanager:
    image: prom/alertmanager:latest
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks: [network_cluster]
    restart: on-failure
    environment:   
      TZ: ${TZ}
    volumes:
      - nfs_alertmanager:/etc/alertmanager
    deploy:
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.metrics == true
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.http.routers.alertmanager.rule=Host(`alertmanager.${DOMAIN_SWARM}`,`alertmanager.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.alertmanager.entrypoints=websecure
        - traefik.http.routers.alertmanager.service=alertmanager
        - traefik.http.routers.alertmanager.middlewares=auth,normal-chain@file
        - traefik.http.services.alertmanager.loadbalancer.server.port=9093
        - homepage.group=Metrics & Monitor
        - homepage.name=AlertManager
        - homepage.icon=alertmanager.png
        - homepage.href=https://alertmanager.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=Prometheus Alert Manager
        - homepage.siteMonitor=http://alertmanager:9093
        - homepage.weight=12

  # SNMP Exporter
  snmp-exporter:
    image: prom/snmp-exporter:v0.22.0
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
    networks: [network_cluster]
    restart: on-failure
    ports:
      - 9116:9116
    environment:
      TZ: ${TZ}
    volumes:
      - nfs_snmp-exporter:/etc/snmp_exporter
    deploy:
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.metrics == true
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # PVE Exporter
  pve-exporter:
    # 3.0之后改了结构，只能固定到2.3.1 
    image: prompve/prometheus-pve-exporter:2.3.1
    networks: [network_cluster]
    restart: on-failure
    ports:
      - 9221:9221
    environment:
      PVE_USER: ${PVE_USER}
      PVE_TOKEN_NAME: ${PVE_TOKEN_NAME} 
      PVE_TOKEN_VALUE: ${PVE_TOKEN_VALUE} 
      PVE_VERIFY_SSL: ${PVE_VERIFY_SSL} 
      TZ: ${TZ}
    volumes:
      - nfs_pve-exporter_src:/usr/lib/python3.11/site-packages/pve_exporter
    deploy:
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.metrics == true
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # PVE Exporter
  pve-exporter3:
    image: prompve/prometheus-pve-exporter:latest
    networks: [network_cluster]
    restart: on-failure
    ports:
      - 9222:9221
    environment:
      PVE_USER: ${PVE_USER}
      PVE_TOKEN_NAME: ${PVE_TOKEN_NAME} 
      PVE_TOKEN_VALUE: ${PVE_TOKEN_VALUE} 
      PVE_VERIFY_SSL: ${PVE_VERIFY_SSL} 
      TZ: ${TZ}
    # volumes:
      # - nfs_pve-exporter_src:/usr/lib/python3.11/site-packages/pve_exporter
    deploy:
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.metrics == true
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # ELK
  elk:
    image: sebp/elk:8.13.4
    networks: [network_cluster]
    restart: on-failure    
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5001:5001"
      # - "5044:5044"  
    environment:
      TZ: ${TZ}  
    volumes:
      - nfs_elk_kibana_conf:/opt/kibana/config             
      - nfs_elk_elasticsearch_conf:/opt/elasticsearch/config   
      - nfs_elk_logstash_conf:/opt/logstash/config    
      - nfs_elk_logstash_pipelines:/etc/logstash/conf.d   
      - nfs_elk_elasticsearch_plugins:/opt/elasticsearch/plugins
      - nfs_elk_elasticsearch_data:/var/lib/elasticsearch
    deploy:
      labels:    
        - traefik.enable=true
        - traefik.http.routers.elk.rule=Host(`elk.${DOMAIN_SWARM}`,`elk.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.elk.entrypoints=websecure
        - traefik.http.routers.elk.service=elk
        - traefik.http.routers.elk.middlewares=auth,normal-chain@file
        - traefik.http.services.elk.loadbalancer.server.port=5601
        - homepage.group=Metrics & Monitor
        - homepage.name=ELK
        - homepage.icon=kibana.png
        - homepage.href=https://elk.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=ELK
        - homepage.siteMonitor=http://elk:5601
        - homepage.weight=20             
      replicas: 1     
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.metrics == true    

  logspout-vm:
    image: gliderlabs/logspout:v3.2.14
    command: syslog+tcp://elk:5000
    networks: [network_cluster]
    # environment:
    #   SYSLOG_STRUCTURED_DATA: "<Loggly Customer Token>@41058"
    #   tag: "<custom tag>"
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      # resources:
      #   limits:
      #     cpus: '0.20'
      #     memory: 256M
      #   reservations:
      #     cpus: '0.10'
      #     memory: 128M      
      placement:
        constraints:
          - node.platform.os == linux    
          - node.labels.type == vm      

  logspout-router:
    image: gliderlabs/logspout:v3.2.14
    command: syslog+tcp://192.168.11.117:5000
    networks: [network_cluster]
    # environment:
    #   SYSLOG_STRUCTURED_DATA: "<Loggly Customer Token>@41058"
    #   tag: "<custom tag>"
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      # resources:
      #   limits:
      #     cpus: '0.20'
      #     memory: 256M
      #   reservations:
      #     cpus: '0.10'
      #     memory: 128M      
      placement:
        constraints:
          - node.role == manager
          - node.labels.type == router

  # swarm-log:
  #   image: bekt/logspout-logstash:latest
  #   networks: [network_cluster]
  #   volumes:
  #     # Logspout reads this in and attaches it to the log
  #     - /etc/hostname:/etc/host_hostname:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     # IP and port for logstash host
  #     - ROUTE_URIS=logstash://192.168.11.117:5001
  #     # Include all docker labels
  #     - DOCKER_LABELS=true
  #     # Add environment field to all logs sent to logstash
  #     # - LOGSTASH_FIELDS=environment=${NODE_ENV}
  #   deploy:
  #     mode: global
  #     # resources:
  #     #   limits:
  #     #     cpus: '0.20'
  #     #     memory: 256M
  #     #   reservations:
  #     #     cpus: '0.10'
  #     #     memory: 128M
  #     placement:
  #       constraints:
  #         - node.platform.os == linux            

  fluentd:
    image: ruanbekker/fluentd-elasticsearch
    networks: [network_cluster]    
    user: root
    environment:
      FLUENTD_CONF: 'fluent.conf'
      FLUENTD_HOSTNAME: '{{.Node.Hostname}}'
    ports:
      - 24224:24224
      - 24224:24224/udp
    # volumes:
    #   - nfs_fluentd_conf:/fluentd/etc/fluent.conf
    configs:
      - source: fluentd_conf.v1
        target: /fluentd/etc/fluent.conf      
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == linux          

  # elasticsearch:
  #   image: elasticsearch:8.13.4
  #   environment:
  #     cluster.name: "elasticsearch" #设置集群名称为elasticsearch
  #     discovery.type: "single-node" #以单一节点模式启动
  #     ES_JAVA_OPTS: "-Xms512m -Xmx512m" #设置使用jvm内存大小      
  #     # ES_JAVA_OPTS: "-Xms2g -Xmx2g" 
  #   volumes:
  #     - nfs_elasticsearch_data:/usr/share/elasticsearch/data
  #     - nfs_elasticsearch_plugins:/usr/share/elasticsearch/plugins
  #     - nfs_elasticsearch_conf:/usr/share/elasticsearch/config
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.labels.type == vm
  #         - node.labels.metrics == true    
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '2'
  #         memory: 2G
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3

  # logstash:
  #   image: logstash:8.13.4
  #   # command: ["logstash","-f","/etc/conf/logstash.conf"]
  #   volumes:
  #     - nfs_logstash_conf:/usr/share/logstash/config
  #   ports:
  #       # - "12201:12201/udp"
  #       - 4560:4560
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.labels.type == vm
  #         - node.labels.metrics == true    
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 1G
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3

  # kibana:
  #   image: kibana:8.13.4
  #   environment:
  #     elasticsearch.hosts: "http://elasticsearch:9200" #设置访问elasticsearch的地址
  #     # ELASTICSEARCH_URL: "http://elasticsearch:9200"
  #   ports:
  #       # - "12201:12201/udp"
  #       - 5601:5601      
  #   volumes:
  #     - nfs_kibana_conf:/usr/share/kibana/config    
  #   deploy:
  #     labels:    
  #       - traefik.enable=true
  #       - traefik.http.routers.kibana.rule=Host(`elk.${DOMAIN_SWARM}`,`elk.${DOMAIN_EMERGENCY}`)
  #       - traefik.http.routers.kibana.entrypoints=websecure
  #       - traefik.http.routers.kibana.service=kibana
  #       - traefik.http.routers.kibana.middlewares=normal-chain@file
  #       - traefik.http.services.kibana.loadbalancer.server.port=5601
  #       - homepage.group=Metrics & Monitor
  #       - homepage.name=ELK
  #       - homepage.icon=kibana.png
  #       - homepage.href=https://elk.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
  #       - homepage.description=ELK
  #       - homepage.siteMonitor=http://kibana:5601
  #       - homepage.weight=20    
  #     placement:
  #       constraints:
  #         - node.labels.type == vm
  #         - node.labels.metrics == true        
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '2'
  #         memory: 1G
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3

  # Node Exporter
  # node-exporter:
  #   image: prom/node-exporter:latest
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
  #   networks: [network_cluster]
  #   restart: on-failure
  #   ports:
  #     - 9100:9100
  #   environment:   
  #     TZ: ${TZ}
  #   volumes:
  #     - /proc:/etc/pve.yml
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints:
  #         - node.platform.os == linux      
  #     resources:
  #       limits:
  #         memory: 128M
  #       reservations:
  #         memory: 64M

  # Cadvisor
  # cadvisor:
  #   image: docker
  #   volumes: 
  #       - /var/run/docker.sock:/var/run/docker.sock
  #   entrypoint: ["/bin/sh","-c"]
  #   networks: [network_cluster]
  #   deploy:
  #     mode: global
  #     restart_policy:
  #       condition: none
  #   ports:
  #     - 18080:8080
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - PARENT={{.Task.Name}}
  #     - CHILDNAME={{.Service.Name}}_sidecar.{{.Node.ID}}.{{.Task.ID}}
  #   command: 
  #   - |
  #     exec docker run -i --rm --network="container:$${PARENT}" \
  #           --env=TZ=Asia/Shanghai \
  #           --volume=/:/rootfs:ro \
  #           --volume=/var/run:/var/run:ro  \
  #           --volume=/var/run/docker.sock:/var/run/docker.sock:ro \
  #           --volume=/sys:/sys:ro  \
  #           --volume=/var/lib/docker/:/var/lib/docker:ro \
  #           --volume=/dev/disk/:/dev/disk:ro \
  #           --name $${CHILDNAME} \
  #           --privileged \
  #           --device=/dev/kmsg \
  #           registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/cadvisor:v0.47.3

  # Cadvisor
  # cadvisor:
  #   # image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/cadvisor:v0.47.3
  #   # image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/cadvisor:v0.44.0
  #   image: starlingx/cadvisor:master-debian-stable-latest
  #   networks: [network_cluster]
  #   devices:
  #     - /dev/kmsg
  #   restart: on-failure
  #   ports:
  #     - "8080:8080"    
  #   environment:
  #     TZ: ${TZ}
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro  
  #     - /dev/disk:/dev/disk:ro
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints:
  #         - node.platform.os == linux

networks:
  network_cluster:
    external: true

configs:
  fluentd_conf.v1:
    external: true

x-common-keys-volume: &common-keys-volume
  type: nfs
  o: addr=${NFS_SERVER},rw,nfsvers=4

volumes:
  # NFS
  nfs_prometheus_conf:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/prometheus/conf
  nfs_prometheus_data:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/prometheus/data
  nfs_alertmanager:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/alertmanager        
  nfs_grafana_data:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/grafana/data        
  nfs_grafana_conf:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/grafana/conf
  nfs_snmp-exporter:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/snmp-exporter
  nfs_pve-exporter_src:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/pve-exporter/prometheus-pve-exporter/src/pve_exporter
  nfs_elk_elasticsearch_data:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/elk/elasticsearch/data
  nfs_elk_elasticsearch_plugins:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/elk/elasticsearch/plugins  
  nfs_elk_elasticsearch_conf:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/elk/elasticsearch/config      
  nfs_elk_logstash_conf:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/elk/logstash/conf  
  nfs_elk_logstash_pipelines:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/elk/logstash/pipelines           
  nfs_elk_kibana_conf:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/metrics/elk/kibana/config         
  # nfs_fluentd_conf:
  #   driver: local
  #   driver_opts:
  #     <<: *common-keys-volume
  #     device: :${NFS_DEVICE}/metrics/fluentd/conf/fluentd.conf          